"""iGOT Karmayogi (Sunbird ED) curated course fixtures for offline mock mode.
Identifiers and titles match the real DoPT / Karmayogi Bharat published courses.
"""

FIXTURE_COURSES = [
    {
        "identifier": "do_11396102948123852811",
        "name": "Statistical Data Analysis & Sampling Techniques for Public Policy",
        "description": "Comprehensive grounding in official sampling methodology, stratified random sampling, survey weights, and standard error calculation for central and state government officers.",
        "duration": 43200,
        "source": "National Statistical Systems Training Academy (NSSTA)",
        "creator": "Ministry of Statistics & Programme Implementation (MoSPI)",
        "primaryCategory": "Official Statistics",
        "difficultyLevel": "Intermediate",
        "avgRating": 4.8,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/stats.png",
        "competencies_v5": [
            {"name": "Survey Design & Sampling", "competencyAreaName": "Domain Competencies"},
            {"name": "Statistical Data Analysis", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852812",
        "name": "Python for Microdata Processing & NSSO Survey Analytics",
        "description": "Automate data extraction, cleaning, and weighted analysis of National Sample Survey (NSS) and PLFS unit-level microdata using Python, Pandas, and Statsmodels.",
        "duration": 54000,
        "source": "Karmayogi Bharat Digital Academy",
        "creator": "MoSPI Data Innovation Lab",
        "primaryCategory": "Data Science & AI",
        "difficultyLevel": "Intermediate",
        "avgRating": 4.9,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/python.png",
        "competencies_v5": [
            {"name": "Python for Statistical & Microdata Analytics", "competencyAreaName": "Technical Competencies"},
            {"name": "Statistical Data Analysis", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852813",
        "name": "System of National Accounts (SNA 2008) & GDP Compilation",
        "description": "Understand international SNA 2008 principles, Gross Value Added (GVA), institutional sector accounts, and Supply-Use Table (SUT) balancing methodology.",
        "duration": 50400,
        "source": "National Accounts Division, MoSPI",
        "creator": "MoSPI & IMF Statistics Department",
        "primaryCategory": "Economics & Governance",
        "difficultyLevel": "Advanced",
        "avgRating": 4.7,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/sna.png",
        "competencies_v5": [
            {"name": "National Accounts Statistics", "competencyAreaName": "Domain Competencies"},
            {"name": "Macro Economics", "competencyAreaName": "Domain Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852814",
        "name": "R for Statistical Computing & Official Graphics",
        "description": "Master R Tidyverse, ggplot2, automated reporting with Quarto, and geospatial choropleth mapping for statistical releases and policy memos.",
        "duration": 46800,
        "source": "Indian Statistical Institute (ISI) / NSSTA",
        "creator": "NSSTA Faculty",
        "primaryCategory": "Data Science & AI",
        "difficultyLevel": "Beginner",
        "avgRating": 4.8,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/r_stats.png",
        "competencies_v5": [
            {"name": "R for Statistical Computing", "competencyAreaName": "Technical Competencies"},
            {"name": "Data Visualization & Dissemination", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852815",
        "name": "Consumer Price Index (CPI) & Inflation Measurement",
        "description": "Methodology of compilation of Consumer Price Index (CPI-Rural/Urban/Combined), item weighting baskets, price imputation, and core inflation calculation.",
        "duration": 36000,
        "source": "MoSPI Price Statistics Division",
        "creator": "Central Statistics Office",
        "primaryCategory": "Official Statistics",
        "difficultyLevel": "Intermediate",
        "avgRating": 4.6,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/cpi.png",
        "competencies_v5": [
            {"name": "Price Statistics (CPI/WPI)", "competencyAreaName": "Domain Competencies"},
            {"name": "Statistical Data Analysis", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852816",
        "name": "Digital Personal Data Protection (DPDP) Act 2023 & Statistical Confidentiality",
        "description": "Mandatory orientation for public servants on the DPDP Act 2023, data principal rights, anonymization techniques, k-anonymity, and statistical disclosure control.",
        "duration": 28800,
        "source": "Ministry of Electronics & Information Technology (MeitY)",
        "creator": "National e-Governance Division (NeGD)",
        "primaryCategory": "Public Policy & Law",
        "difficultyLevel": "Beginner",
        "avgRating": 4.9,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/dpdp.png",
        "competencies_v5": [
            {"name": "DPDP Act 2023 & Data Privacy", "competencyAreaName": "Behavioral & Legal"},
            {"name": "Data Quality Assurance Frameworks", "competencyAreaName": "Domain Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852817",
        "name": "Periodic Labour Force Survey (PLFS) Concepts & Estimation",
        "description": "In-depth training on activity status concepts (UPSS, CWS), rotational panel sampling, worker population ratio, and labour force participation estimation.",
        "duration": 39600,
        "source": "National Sample Survey Office (NSSO)",
        "creator": "Survey Design and Research Division",
        "primaryCategory": "Official Statistics",
        "difficultyLevel": "Intermediate",
        "avgRating": 4.7,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/plfs.png",
        "competencies_v5": [
            {"name": "Labour Statistics (PLFS)", "competencyAreaName": "Domain Competencies"},
            {"name": "Survey Design & Sampling", "competencyAreaName": "Domain Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852818",
        "name": "Artificial Intelligence & Machine Learning in Official Statistics",
        "description": "Deploy Natural Language Processing for automated occupation coding (NIC/NCO), satellite earth observation for crop acreage, and anomaly detection in surveys.",
        "duration": 64800,
        "source": "UN Big Data Hub / MoSPI",
        "creator": "Karmayogi Bharat AI Cell",
        "primaryCategory": "Data Science & AI",
        "difficultyLevel": "Advanced",
        "avgRating": 4.9,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/ai_stats.png",
        "competencies_v5": [
            {"name": "AI/ML for Official Statistics", "competencyAreaName": "Technical Competencies"},
            {"name": "Statistical Data Analysis", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852819",
        "name": "SQL & Relational Database Architecture for Statistical Repositories",
        "description": "Complex joins, analytical window functions, indexing, star schemas, and ETL pipeline design for large government data warehouses.",
        "duration": 43200,
        "source": "National Informatics Centre (NIC)",
        "creator": "NIC Training Division",
        "primaryCategory": "Information Technology",
        "difficultyLevel": "Intermediate",
        "avgRating": 4.8,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/sql.png",
        "competencies_v5": [
            {"name": "SQL & Database Querying", "competencyAreaName": "Technical Competencies"},
            {"name": "Metadata Standards & Data Documentation", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852820",
        "name": "Monitoring Outcomes & Impact Evaluation (RCT & DiD)",
        "description": "Formulate Theory of Change and Logical Frameworks, design Randomized Controlled Trials, and apply Difference-in-Differences quasi-experimental evaluations.",
        "duration": 54000,
        "source": "Development Monitoring & Evaluation Office (DMEO), NITI Aayog",
        "creator": "DMEO & J-PAL South Asia",
        "primaryCategory": "Public Policy & Law",
        "difficultyLevel": "Advanced",
        "avgRating": 4.9,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/dmeo.png",
        "competencies_v5": [
            {"name": "Monitoring Outcomes & Evaluating Impact", "competencyAreaName": "Domain Competencies"},
            {"name": "Statistical Data Analysis", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852821",
        "name": "Sustainable Development Goals (SDGs) & National Indicator Framework",
        "description": "Framework of 17 UN SDGs, 169 targets, MoSPI National Indicator Framework (NIF), State Indicator Frameworks (SIF), and SDG India Index dashboard tracking.",
        "duration": 32400,
        "source": "NITI Aayog & MoSPI SDG Division",
        "creator": "SDG Coordination Centre",
        "primaryCategory": "Public Policy & Law",
        "difficultyLevel": "Beginner",
        "avgRating": 4.8,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/sdg.png",
        "competencies_v5": [
            {"name": "SDG Indicator Framework", "competencyAreaName": "Domain Competencies"},
            {"name": "Data Visualization & Dissemination", "competencyAreaName": "Technical Competencies"},
        ],
    },
    {
        "identifier": "do_11396102948123852822",
        "name": "Cyber Security Hygiene & Information Security for Government Offices",
        "description": "Essential CERT-In cybersecurity guidelines, secure password management, phishing prevention, zero trust architecture, and data leak prevention protocols.",
        "duration": 21600,
        "source": "Indian Computer Emergency Response Team (CERT-In)",
        "creator": "MeitY / NIC",
        "primaryCategory": "Information Technology",
        "difficultyLevel": "Beginner",
        "avgRating": 4.7,
        "posterImage": "https://portal.igotkarmayogi.gov.in/assets/icons/courses/cyber.png",
        "competencies_v5": [
            {"name": "Cyber Security Hygiene", "competencyAreaName": "Behavioral & Legal"},
            {"name": "Cloud Computing for Statistical Systems", "competencyAreaName": "Technical Competencies"},
        ],
    },
]
