from typing import List, Optional, Any, Dict
from pydantic import BaseModel, HttpUrl, Field
from app.models.learning import SourceClassEnum, VerificationStatusEnum, CourseStatusEnum, TopicProgressStatusEnum


class LearningResourceBase(BaseModel):
    id: str
    topic_id: str
    title: str
    description: str = ""
    url: str
    resource_type: str
    provider: str
    source_domain: str
    source_class: SourceClassEnum = SourceClassEnum.OTHER
    language: str = "English"
    difficulty: str = "Intermediate"
    estimated_minutes: int = 15
    is_free: bool = True
    is_official: bool = False
    download_url: Optional[str] = None
    thumbnail_url: Optional[str] = None
    published_date: Optional[str] = None
    last_verified: str = "04 Sep 2026"
    verification_status: VerificationStatusEnum = VerificationStatusEnum.VERIFIED
    quality_score: int = 85
    order_index: int = 0
    is_completed: bool = False


class LearningTopicBase(BaseModel):
    id: str
    module_id: str
    topic_number: int
    title: str
    description: str = ""
    estimated_minutes: int = 20
    difficulty: str = "Intermediate"
    competency_id: Optional[str] = None
    skill_level: str = "L3"
    prerequisites: List[str] = []
    learning_objectives: List[str] = []
    exercises: List[Dict[str, Any]] = []
    order_index: int = 0
    status: TopicProgressStatusEnum = TopicProgressStatusEnum.NOT_STARTED
    completed_at: Optional[str] = None
    time_spent_seconds: int = 0
    resources: List[LearningResourceBase] = []


class LearningModuleBase(BaseModel):
    id: str
    course_id: str
    module_number: int
    title: str
    description: str = ""
    duration: str = "2 hours"
    order_index: int = 0
    completed_topics_count: int = 0
    total_topics_count: int = 0
    completion_percentage: float = 0.0
    topics: List[LearningTopicBase] = []


class CourseCurriculumResponse(BaseModel):
    course_id: str
    course_title: str
    provider: str
    domain: str
    duration: str
    difficulty: str
    language: str
    role_relevance: float = 95.0
    skill_gap_relevance: str = "High"
    current_proficiency: str = "L2 (48%)"
    target_proficiency: str = "L4 (75%)"
    completion_percentage: float = 0.0
    total_modules_count: int = 0
    total_topics_count: int = 0
    completed_topics_count: int = 0
    modules: List[LearningModuleBase] = []


class TopicCompletionRequest(BaseModel):
    time_spent_seconds: int = 300


class TopicCompletionResponse(BaseModel):
    success: bool
    topic_id: str
    status: str
    completed_at: str
    module_id: str
    module_completion_percentage: float
    course_id: str
    course_completion_percentage: float
    digital_twin_updated: bool = False
    competency_gain: Optional[float] = None
    new_competency_score: Optional[float] = None
    new_role_readiness: Optional[float] = None


class ResourceProgressRequest(BaseModel):
    is_completed: bool = True


class GenerateNotesRequest(BaseModel):
    topic_id: str
    include_formulas: bool = True
    include_mospi_relevance: bool = True


class StudyNotesResponse(BaseModel):
    topic_id: str
    topic_title: str
    course_title: str
    competency_name: str
    generated_date: str = "04 Sep 2026"
    overview: str
    key_concepts: List[str]
    definitions: List[Dict[str, str]]
    important_formulas: List[Dict[str, str]]
    government_statistics_relevance: str
    practical_example: Dict[str, str]
    common_mistakes: List[str]
    interview_questions: List[Dict[str, str]]
    self_test_questions: List[Dict[str, Any]]
    verified_sources: List[Dict[str, str]]
    attribution: str = "Generated by StatIntel AI. Based on verified official publications and documentation."


class CatalogCourseResponse(BaseModel):
    id: str
    course_code: str
    title: str
    description: str
    provider: str
    provider_type: str
    role: str
    roles_supported: List[str]
    department: str
    domain: str
    competencies_covered: List[str]
    duration: str
    duration_hours: float
    delivery_mode: str
    eligibility: str
    level: str
    source_class: SourceClassEnum
    official_url: Optional[str]
    source_url: str
    last_verified: str
    status: CourseStatusEnum
    verification_status: VerificationStatusEnum
    modules_count: int
    topics_count: int
    is_mandatory_for_role: bool


class ModuleAssessmentSubmitRequest(BaseModel):
    user_answers: List[int]
    time_spent_seconds: int = 180


class ModuleAssessmentResultResponse(BaseModel):
    module_id: str
    score: int
    total: int
    accuracy: float
    passed: bool
    competency_boost: float
    new_competency_score: float
    new_role_readiness: float
    completed_at: str
    answers_feedback: List[Dict[str, Any]]
